[package]
name = "matuv"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
dialoguer = "0.11.0"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }

[profile.release]
opt-level = 3
